# Desafío Guiado 2

1)Importa pandas y numpy siguiendo las convenciones.

● Lee la base de datos worldcup2014.csv y asígnela a un objeto df.

● Solicita las primeras 5 observaciones con head.

In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('worldcup2014.csv')
df.head()

,team,continent,group,group_pos,cantidad_juegos,juegos_ganados,juegos_empatados,juegos_perdidos,goles_favor,goles_contra,goles_diferencia,puntos,clasificado
0,Brazil,southamerica,A,1,3,2,1,0,7,2,5,7,1
1,Mexico,northamerica,A,2,3,2,1,0,4,1,3,7,1
2,Croatia,europe,A,3,3,1,0,2,6,6,0,3,0
3,Cameroon,africa,A,4,3,0,0,3,1,9,−8,0,0
4,Netherlands,europe,B,1,3,3,0,0,10,3,7,9,1

2) Frecuencia de continent: utilizando value_counts responde lo siguiente:

● ¿Cuál es el continente con una mayor presencia en la muestra?

● ¿Cuál es la probabilidad de elegir un equipo asiático al azar?

● ¿Cuál es la probabilidad de elegir un equipo africano al azar?

In [13]:
serie_continent = df['continent']
serie_continent.value_counts()

europe          13
southamerica     6
africa           5
northamerica     4
asia             4
Name: continent, dtype: int64

In [18]:
prob_asia = serie_continent.value_counts('%').get('asia')
print("La probabilidad de que aparezca un equipo asiatico es de : {}%".format(100 * prob_asia))

La probabilidad de que aparezca un equipo asiatico es de : 12.5%

In [19]:
prob_africa = serie_continent.value_counts('%').get('africa')
print("La probabilidad de que aparezca un equipo asiatico es de : {}%".format(100 * prob_africa))

La probabilidad de que aparezca un equipo asiatico es de : 15.625%

3) Generación de un subconjunto de datos: por cada continente, genere un nuevo objeto que almacene sólo las observaciones del continente.

In [23]:
#se puede utilizar el .query!
africa_df = df[df['continent'] == 'africa']
europe_df = df[df['continent'] == 'europe']
asia_df = df[df['continent'] == 'asia']
northamerica_df = df[df['continent'] == 'northamerica']
southamerica_df = df[df['continent'] == 'southamerica']

4) Probabilidad de clasificación a la siguiente ronda: calcula la probabilidad de que un país pase a la siguiente ronda (clasifique) por continente.

● ¿Cuál es la probabilidad de que un país asiático pase a la siguiente ronda?

● ¿Cuáles son los dos continentes con la mayor probabilidad de clasificar?

● ¿Cuál es la probabilidad de que un país europeo no clasifique?

In [30]:
def calc_prob_clasif(df):
    probabilidades = df['clasificado'].value_counts(normalize = True)
    return probabilidades

In [31]:
calc_prob_clasif(asia_df)

0    1.0
Name: clasificado, dtype: float64

In [34]:
print('africa')
print(calc_prob_clasif(africa_df))
print(' ')
print('europe')
print(calc_prob_clasif(europe_df))
print(' ')
print('asia')
print(calc_prob_clasif(asia_df))
print(' ')
print('northamerica')
print(calc_prob_clasif(northamerica_df))
print(' ')
print('southamerica')
print(calc_prob_clasif(southamerica_df))
print(' ')

africa
0    0.6
1    0.4
Name: clasificado, dtype: float64

europe
0    0.538462
1    0.461538
Name: clasificado, dtype: float64

asia
0    1.0
Name: clasificado, dtype: float64

northamerica
1    0.75
0    0.25
Name: clasificado, dtype: float64

southamerica
1    0.833333
0    0.166667
Name: clasificado, dtype: float64

In [48]:
continentes_df = [
    africa_df.copy(), 
    europe_df.copy(),
    asia_df.copy(),
    northamerica_df.copy(),
    southamerica_df.copy()
]

for n_iter in continentes_df:
    print(" ")
    print("Nombre Continente:")
    print(n_iter.iloc[0,1])
    print("Probabilidad de Clasificación:")
    print(n_iter['clasificado'].value_counts(normalize=True))

Nombre Continente:
africa
Probabilidad de Clasificación:
0    0.6
1    0.4
Name: clasificado, dtype: float64

Nombre Continente:
europe
Probabilidad de Clasificación:
0    0.538462
1    0.461538
Name: clasificado, dtype: float64

Nombre Continente:
asia
Probabilidad de Clasificación:
0    1.0
Name: clasificado, dtype: float64

Nombre Continente:
northamerica
Probabilidad de Clasificación:
1    0.75
0    0.25
Name: clasificado, dtype: float64

Nombre Continente:
southamerica
Probabilidad de Clasificación:
1    0.833333
0    0.166667
Name: clasificado, dtype: float64

In [51]:
df.groupby('continent')['clasificado'].value_counts('%')

continent     clasificado
africa        0              0.600000
              1              0.400000
asia          0              1.000000
europe        0              0.538462
              1              0.461538
northamerica  1              0.750000
              0              0.250000
southamerica  1              0.833333
              0              0.166667
Name: clasificado, dtype: float64

5) Probabilidad de victoria y derrota: se pide utilizar value_counts para calcular la probabilidad de que un continente contenga países con o sin victorias. Para ello crea una columna adicional llamada 'ha_ganado' que contenga un 0 si es que un país no tiene juegos ganados y un 1 si es que ha ganado al menos un juego.

Con base en el resultado del procedimiento recién descrito, responda lo
siguiente:

A. ¿Qué continente tiene la mayor probabilidad de tener países con al menos 1 victoria?

B. ¿Qué continente tiene un nivel similar entre países que tienen o no tienen victorias?

Reformule el código para juegos perdidos y analice los continentes con mayor probabilidad de tener países sin juegos perdidos.

In [55]:
for iter_continent in continentes_df:
    iter_continent['ha_ganado'] = np.where(iter_continent['juegos_ganados'] > 0, 1, 0)
    print(iter_continent['ha_ganado'].value_counts(normalize=True))

1    0.6
0    0.4
Name: ha_ganado, dtype: float64
1    0.846154
0    0.153846
Name: ha_ganado, dtype: float64
0    1.0
Name: ha_ganado, dtype: float64
1    0.75
0    0.25
Name: ha_ganado, dtype: float64
1    1.0
Name: ha_ganado, dtype: float64

In [14]:
df['ha_ganado'] = np.where(df['juegos_ganados'] > 0, 1, 0)
df

,team,continent,group,group_pos,cantidad_juegos,juegos_ganados,juegos_empatados,juegos_perdidos,goles_favor,goles_contra,goles_diferencia,puntos,clasificado,ha_ganado
0,Brazil,southamerica,A,1,3,2,1,0,7,2,5,7,1,1
1,Mexico,northamerica,A,2,3,2,1,0,4,1,3,7,1,1
2,Croatia,europe,A,3,3,1,0,2,6,6,0,3,0,1
3,Cameroon,africa,A,4,3,0,0,3,1,9,−8,0,0,0
4,Netherlands,europe,B,1,3,3,0,0,10,3,7,9,1,1
5,Chile,southamerica,B,2,3,2,0,1,5,3,2,6,1,1
6,Spain,europe,B,3,3,1,0,2,4,7,−3,3,0,1
7,Australia,asia,B,4,3,0,0,3,3,9,−6,0,0,0
8,Colombia,southamerica,C,1,3,3,0,0,9,2,7,9,1,1
9,Greece,europe,C,2,3,1,1,1,2,4,−2,4,1,1
10,Ivory Coast,africa,C,3,3,1,0,2,4,5,−1,3,0,1
11,Japan,asia,C,4,3,0,1,2,2,6,−4,1,0,0
12,Costa Rica,northamerica,D,1,3,2,1,0,4,1,3,7,1,1
13,Uruguay,southamerica,D,2,3,2,0,1,4,4,0,6,1,1
14,Italy,europe,D,3,3,1,0,2,2,3,−1,3,0,1
15,England,europe,D,4,3,0,1,2,2,4,−2,1,0,0
16,France,europe,E,1,3,2,1,0,8,2,6,7,1,1
17,Switzerland,europe,E,2,3,2,0,1,7,6,1,6,1,1
18,Ecuador,southamerica,E,3,3,1,1,1,3,3,0,4,0,1
19,Honduras,northamerica,E,4,3,0,0,3,1,8,−7,0,0,0
20,Argentina,southamerica,F,1,3,3,0,0,6,3,3,9,1,1
21,Nigeria,africa,F,2,3,1,1,1,3,3,0,4,1,1
22,Bosnia and Herzegovina,europe,F,3,3,1,0,2,4,4,0,3,0,1
23,Iran,asia,F,4,3,0,1,2,1,4,−3,1,0,0
24,Germany,europe,G,1,3,2,1,0,7,2,5,7,1,1
25,United States,northamerica,G,2,3,1,1,1,4,4,0,4,1,1
26,Portugal,europe,G,3,3,1,1,1,4,7,−3,4,0,1
27,Ghana,africa,G,4,3,0,1,2,4,6,−2,1,0,0
28,Belgium,europe,H,1,3,3,0,0,4,1,3,9,1,1
29,Algeria,africa,H,2,3,1,1,1,6,5,1,4,1,1
30,Russia,europe,H,3,3,0,2,1,2,3,−1,2,0,0
31,South Korea,asia,H,4,3,0,1,2,3,6,−3,1,0,0

In [19]:
victorias_por_continente = df.groupby('continent')['ha_ganado'].value_counts()
victorias_por_continente

continent     ha_ganado
africa        1             3
              0             2
asia          0             4
europe        1            11
              0             2
northamerica  1             3
              0             1
southamerica  1             6
Name: ha_ganado, dtype: int64

In [20]:
perdedores_por_continente = df.groupby('continent')['ha_ganado'].value_counts(normalize=True)
perdedores_por_continente

continent     ha_ganado
africa        1            0.600000
              0            0.400000
asia          0            1.000000
europe        1            0.846154
              0            0.153846
northamerica  1            0.750000
              0            0.250000
southamerica  1            1.000000
Name: ha_ganado, dtype: float64

In [22]:
probs = df.groupby('continent')['ha_ganado'].value_counts(normalize=True)

In [23]:
max_prob = probs.max()
continente_max_prob = probs[probs == max_prob].index[0][0]

In [24]:
print(f'El continente con la mayor probabilidad de tener países con al menos 1 victoria es {continente_max_prob}')

El continente con la mayor probabilidad de tener países con al menos 1 victoria es asia

In [27]:
similares = probs[probs.abs() < 0.3]
continentes_similares = similares.index.get_level_values(0).unique()
continentes_similares

Index(['europe', 'northamerica'], dtype='object', name='continent')

In [28]:
print(f'Los continentes con una distribución similar entre países que tienen o no tienen victorias son Europa y Norte América')

Los continentes con una distribución similar entre países que tienen o no tienen victorias son Europa y Norte América